#ifndef _UMACORECONSTANT_
#define _UMACORECONSTANT_

#include "Global.h"
#include "UMAException.h"

namespace UMACoreConstant {
	enum UMA_OBJECT { WORLD, EXPERIMENT, AGENT, SNAPSHOT, DATA_MANAGER, SENSOR, ATTR_SENSOR, SENSOR_PAIR, ATTR_SENSOR_PAIR };
	enum UMA_AGENT { AGENT_STATIONARY, AGENT_QUALITATIVE, AGENT_DISCOUNTED, AGENT_EMPIRICAL };
	enum UMA_SNAPSHOT { SNAPSHOT_STATIONARY, SNAPSHOT_QUALITATIVE, SNAPSHOT_DISCOUNTED, SNAPSHOT_EMPIRICAL };

	string DLL_PUBLIC getUMAObjName(const UMA_OBJECT &obj);
	string DLL_PUBLIC getUMAAgentName(const UMA_AGENT &agent);
	string DLL_PUBLIC getUMASnapshotName(const UMA_SNAPSHOT &snapshot);
	UMA_SNAPSHOT DLL_PUBLIC getUMASnapshotTypeByAgent(const UMA_AGENT &agent);
}
#endif